### ISSUE TITLE
build failed in ubuntu 18.04

### ISSUE THREAD

**Issue by KevinSYT** [emqx/emqx-rel#194]
master branch build failed in ubuntu 18.04.

_==> cuttlefish (compile)
Compiled src/cuttlefish_duration_parse.peg
Compiled src/conf_parse.peg
Compiled src/cuttlefish_vmargs.erl
Compiled src/cuttlefish_duration.erl
Compiled src/cuttlefish_enum.erl
Compiled src/cuttlefish_translation.erl
Compiled src/cuttlefish_validator.erl
src/cuttlefish_unit.erl:3: can't find include lib "eunit/include/eunit.hrl"
src/cuttlefish_unit.erl:72: undefined macro 'assertEqual/2'
src/cuttlefish_unit.erl:96: undefined macro 'assertMatch/2'
src/cuttlefish_unit.erl:101: undefined macro 'assertMatch/2'
src/cuttlefish_unit.erl:106: function assert_error_in_phase/2 undefined
src/cuttlefish_unit.erl:118: function assert_error_in_phase/2 undefined
src/cuttlefish_unit.erl:124: function assert_error/1 undefined
src/cuttlefish_unit.erl:4: Warning: export_all flag enabled - all functions will be exported
ERROR: compile failed while processing /home/kevin/Downloads/emq-relx-2.3.7/deps/cuttlefish: rebar_abort
Makefile:17: recipe for target 'compile' failed
make[2]: *** [compile] Error 1
make[2]: Leaving directory '/home/kevin/Downloads/emq-relx-2.3.7/deps/cuttlefish'
../../erlang.mk:312: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/kevin/Downloads/emq-relx-2.3.7/deps/emqttd'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2_

**Comment by huangdan** [comment]
@KevinSYT 
I can't reproduce this issue, but I guess it might send a lost packet during the compilation download and you can try to do it:
`rm -rf deps/cuttlefish `
then, `make`

**Comment by ningpeng** [comment]
CentOS Linux release 7.2 (Final)
 erl -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:10] [hipe] [kernel-poll:false]

emqx-2.3.11]# make
make[1]: Entering directory `/data/home/ningpeng/emqx-2.3.11/deps/cuttlefish'
./rebar get-deps
==> getopt (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> neotoma (get-deps)
==> cuttlefish (get-deps)
./rebar compile
==> getopt (compile)
==> goldrush (compile)
==> lager (compile)
==> neotoma (compile)
==> cuttlefish (compile)
src/cuttlefish_unit.erl:none: undefined parse transform 'lager_transform'
ERROR: compile failed while processing /data/home/ningpeng/emqx-2.3.11/deps/cuttlefish: rebar_abort
make[1]: *** [compile] Error 1
make[1]: Leaving directory `/data/home/ningpeng/emqx-2.3.11/deps/cuttlefish'
make: *** [deps] Error 2

BUT
Erlang/OTP 21 works well.

**Comment by wilddragon** [comment]
please pay attention to the  rebar file used by the Makefile,  all the deps should use same rebar version
some deps attached rebar itself.   you can download the latest version from www.rebar3.org and save it to your path,  and use this rebar at all the Make in the deps path.

**Comment by wilddragon** [comment]
mochiweb  attached rebar itself,  if it is different with the one at cuttlefish directory, you can use same rebar .
