### ISSUE TITLE
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx-rel#249]
```
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /root/emqx/deps
          /usr/local/lib/erlang/lib
          /root/emqx/apps
===> Resolved emqx-3.0
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
root@15e45d27b0f7:~/emqx# ls
Dockerfile  LICENSE  Makefile  README.md  _rel	bin  ct  data  deps  docker-compose.yml  erlang.mk  rel  relx  relx.config  vars.config
root@15e45d27b0f7:~/emqx# ./_rel/emqx/
bin/         data/        erts-10.1.1/ etc/         hook_lua/    lib/         log/         releases/
root@15e45d27b0f7:~/emqx# ./_rel/emqx/bin/emqx console
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done
```

I am using erlang:latest to build the image. erlang:latest is based on ubuntu. I am building and running it within docker.

**Comment by Gilbert-Wong** [comment]
The erlang/otp is not installed correctly on your system. Please use solution of [erlang-solution](https://www.erlang-solutions.com/resources/download.html) to install erlang/otp 21 on your system.

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong tried with esl-erlang same issue.

**Comment by Gilbert-Wong** [comment]
Which branch do you use ? I suggest you to checkout the tag `v3.0-rc.3` , then build it. By the way, yesterday I build emqx_rel on my ubuntu 18.04 machine which is installed esl-erlang. It has no problem.

**Comment by s4kibs4mi** [comment]
@s4kibs4mi I was trying with emqx30

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong  tried with https://github.com/emqx/emqx-rel/archive/v3.0-beta.3.zip and esl-erlang but no luck yet. can you please check ?

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong **v3.0-rc.3.zip** is broken as well. Finally **emqx30_release** worked with erlang:21 image.
