### ISSUE TITLE
Want to integrate observer module into emqttd in docker

### ISSUE THREAD

**Issue by turengege** [emqx/emqx-rel#252]
Hi 
I try to build emq from source in docker but failed.
env:
> EMQ:2.3.11
Erlang/OTP : install from [rabbitmq/erlang-rpm](https://github.com/rabbitmq/erlang-rpm/releases)
erl:Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
os:centos7

output:
```
make[1]: Leaving directory `/emqttd/deps/emq_auth_jwt'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /emqttd/deps
          /usr/lib64/erlang/lib
          /emqttd/apps
===> Failed to solve release:
 Dependency observer is specified as a dependency but is not reachable by the system.
```

**Comment by Gilbert-Wong** [comment]
In the emqx-rel project, you will find that there is a file named `relx.config`. It specified the erlang library of emqx used. Generally, the observer module depend gui widget and emqx usually ran on the server which has no gui. So we do not think it is a good idea to integrate this module into the runtime of emqx. If you insist doing that, you should add the `ws` and `observer` into relx.config.

![image](https://user-images.githubusercontent.com/20479699/48888782-b973fe00-ee6e-11e8-9978-37172bca6509.png)
