### ISSUE TITLE
Installing From Source failed

### ISSUE THREAD

**Issue by starlily** [emqx/emqx-rel#282]
I failed to install from source, and got error as follow:

![-1](https://user-images.githubusercontent.com/37144207/49916554-7ee20c00-fed6-11e8-8409-3198db0492f0.png)

How to resolve it? Thank you!

**Comment by Gilbert-Wong** [comment]
You could checkout to the win30 branch of emqx-rel and then build again. Giving up build emqx on windows is a better choice.

**Comment by FairyYao** [comment]
hello, I have the same problem with you.Did you solve it?

**Comment by starlily** [comment]
I have selected the correct version, but got problem as follows:
![01](https://user-images.githubusercontent.com/37144207/49926486-9d57ff80-fef6-11e8-9c92-0b9df9bd8ef6.jpg)

**Comment by starlily** [comment]
everything is ok, thank you!

**Comment by Gilbert-Wong** [comment]
We have discarded goldrush which was emqx dependency. Which branch and which tag of emqx did you use?

Gilbert Wong
On Dec 14, 2018, 12:26 PM +0800, starlily <notifications@github.com>, wrote:

Even if I deleted the d:/emqttd/deps/goldrush, make again, it can't be solved.

**Comment by starlily** [comment]
emqtt Release v2.3.11
![00](https://user-images.githubusercontent.com/37144207/49984954-2299ed80-ffa5-11e8-9344-f2772d59f787.jpg)

**Comment by starlily** [comment]
Thank for your advice. Now windows platform cannot change  and i need to compile kafka plugin, so have to intall emq source code.

**Comment by huangguozhen** [comment]
@starlily do have a kafka plugin。

**Comment by Gilbert-Wong** [comment]
Hi, @starlily , kafka plugin ? Sorry, I don't get it. The kafka plugin of emqx is only supported by emqx enterprise edition and it is not open sourced. Could you please give me more details?

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
