### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by limjiregister** [emqx/emqx-rel#299]
#### Environment

- OS: centos7
- Erlang/OTP: 21
- EMQ: 2.3.11

#### Description

*A description of the issue*
make[2]: Entering directory `/home/emqx-rel-2.3.11/deps/jwerl'
===> Package <<"rebar3_elixir">> not found. Fetching registry updates and trying again...
===> Updating package registry...
=INFO REPORT==== 6-Jan-2019::05:24:15.752280 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> Plugin rebar3_elixir not available. It will not be used.
===> Package <<"rebar3_hex">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Plugin rebar3_hex not available. It will not be used.
=INFO REPORT==== 6-Jan-2019::05:24:16.039166 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> Package <<"rebar3_lint">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Plugin rebar3_lint not available. It will not be used.
=INFO REPORT==== 6-Jan-2019::05:24:16.832301 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> No entry for profile default in config.
===> Package <<"rebar3_elixir">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Plugin rebar3_elixir not available. It will not be used.
=INFO REPORT==== 6-Jan-2019::05:24:17.109498 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> Package <<"rebar3_hex">> not found. Fetching registry updates and trying again...
===> Updating package registry...
=INFO REPORT==== 6-Jan-2019::05:24:17.365651 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> Plugin rebar3_hex not available. It will not be used.
===> Package <<"rebar3_lint">> not found. Fetching registry updates and trying again...
===> Updating package registry...
=INFO REPORT==== 6-Jan-2019::05:24:18.703347 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> Plugin rebar3_lint not available. It will not be used.
===> Package jsx-2.9.0 not found. Fetching registry updates and trying again...
===> Updating package registry...
=INFO REPORT==== 6-Jan-2019::05:24:19.013413 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make[2]: *** [compile-erl] Error 1
make[2]: Leaving directory `/home/emqx-rel-2.3.11/deps/jwerl'
make[1]: *** [deps] Error 2
make[1]: Leaving directory `/home/emqx-rel-2.3.11/deps/emq_auth_jwt'
make: *** [deps] Error 2

**Comment by Gilbert-Wong** [comment]
Sorry, For emqttd 2.3.11 , you have to use erlang/otp 20 to build it. We have release emqx3.0.0. It has more features and better performance and you could try to build it with erlang/otp 21. Maybe emqx 3.0.0 is a better choice for you.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
