### ISSUE TITLE
not going well

### ISSUE THREAD

**Issue by limjiregister** [emqx/emqx-rel#300]
#### Environment

- OS: centos
- Erlang/OTP: 20
- EMQ: 2.3.11

#### Description
many many times try to execute MAKE， but always this result。
*A description of the issue*

`make[2]: Entering directory `/home/emqx-rel-2.3.11/deps/jwerl'
===> No entry for profile default in config.
===> Verifying dependencies...
===> Compiling jwerl
make[2]: Leaving directory `/home/emqx-rel-2.3.11/deps/jwerl'
make[1]: Leaving directory `/home/emqx-rel-2.3.11/deps/emq_auth_jwt'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/emqx-rel-2.3.11/deps
          /usr/lib64/erlang/lib
          /home/emqx-rel-2.3.11/apps
===> Failed to solve release:
 Dependency observer is specified as a dependency but is not reachable by the system.

make: *** [relx-rel] Error 127
`

**Comment by Gilbert-Wong** [comment]
The erlang/otp you installed on your machine did not include the library `observer`. You have a choice to remove observer in relx.config by deleting `{observer, load}` in relx.config.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
