### ISSUE TITLE
What's the difference between emqx-rel-2.3.11.tar.gz and emqttd-centos7-v2.3.11.zip?

### ISSUE THREAD

**Issue by wigginskuang** [emqx/emqx-rel#310]
#### Environment

- OS: centos7
- Erlang/OTP: erlang20
- EMQ: emqtt2.3.11

#### Description

*A description of the issue*

**Comment by turtleDeng** [comment]
emqx-rel is a build project for building emqx

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
