### ISSUE TITLE
Error: No Makefile to build dependency /root/emqx-rel-2.3.11/deps/goldrush.

### ISSUE THREAD

**Issue by wigginskuang** [emqx/emqx-rel#311]
#### Environment

- OS: centos7
- Erlang/OTP: erlang20.3
- EMQ: emqx-rel-2.3.11

#### Description
when i make but failed

`[root@MQTT emqx-rel-2.3.11]# make
 DEP    emq_retainer

 DEP    emq_recon
 DEP    emq_reloader
 DEP    emq_auth_clientid
 DEP    emq_auth_username
 DEP    emq_auth_ldap
 DEP    emq_auth_http
 DEP    emq_auth_mysql
 DEP    emq_auth_pgsql
 DEP    emq_auth_redis
 DEP    emq_auth_mongo
 DEP    emq_sn
 DEP    emq_coap
 DEP    emq_stomp
 DEP    emq_plugin_template
 DEP    emq_web_hook
 DEP    emq_lua_hook
 DEP    emq_auth_jwt
Error: No Makefile to build dependency /root/emqx-rel-2.3.11/deps/goldrush.
make: *** [deps] Error 2
`

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have compiled with rebar3, please use the latest version to compile.
