### ISSUE TITLE
Unable to copy from deps/emqx_psk_file/etc/psk.txt to etc/psk.txt 

### ISSUE THREAD

**Issue by li8** [emqx/emqx-rel#322]
#### Environment

- OS: High Sierra (Mac OS) 
- Erlang/OTP: 21.2.4
- EMQ: 3.1

#### Description

On building the system with make , I get the following error 
`Unable to copy from emqx-rel/deps/emqx_psk_file/etc/psk.txt to emqx-rel/_rel/emqx/etc/psk.txt because of {copy_failed,
                                                                                                                                                                        enoent}`

This is because of the latest changes to relx.config for psk
`    {copy, "deps/emqx_psk_file/etc/psk.txt", "etc/psk.txt"}`

As there is no such file in the project emqx-psk-file 
`https://github.com/emqx/emqx-psk-file/tree/master/etc` 

The build works fine, but it only throws error for the last line to copy the text file to etc.

**Comment by li8** [comment]
This is a simple fix: https://github.com/emqx/emqx-psk-file/pull/2

**Comment by turtleDeng** [comment]
The problem has been fixed in https://github.com/emqx/emqx-psk-file/pull/2
