### ISSUE TITLE
protocolVersion = 5 can't work

### ISSUE THREAD

**Issue by WengangChen** [emqx/emqx-rel#323]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 21
- EMQ: release-3.0

#### Description

this problem only occur by use protocolVersion = 5。

I try to use client(mqtt.js: from `npm -i mqtt`) to connect emqx with `protocolVersion 5`，but it can't work.
the connect code is
 `
var ret = require("mqtt").connect("192.168.21.129", {protocolVersion:5, protocol: 'mqtt', prot:1883});
`
The tcp between server to client is connected, but the server not deal the connect packet.

I use `tcpdump` to catch packet form `port 1883`, the result is 

[https://paste.ubuntu.com/p/YpmVQmyqfg/](url)
It seem to the client send the connect request, but server do nothing.
And the program no run into `emqx_protocol.erl`.

# sorry that my poor English

**Comment by linjunjj** [comment]
Hi@WengangChen  Please provide emqx log information

**Comment by WengangChen** [comment]
Sorry,tomorrw ok?
the log only have connection{ idle_timeout} it seem to tcp keepalive timeout .
Tomorrow I will give you the full log,thanks

**Comment by WengangChen** [comment]
@linjunjj 
the `log` paste here
[https://paste.ubuntu.com/p/868sc98SBG/]

**Comment by WengangChen** [comment]
[https://paste.ubuntu.com/p/868sc98SBG/](url)
@linjunjj

**Comment by linjunjj** [comment]
@WengangChen  Client idle timeout, It seems to be `mqtt.js' is problem.
