### ISSUE TITLE
Update Readme :  X is not a valid branch

### ISSUE THREAD

**Issue by TheBeachMaster** [emqx/emqx-rel#335]
#### Environment

- OS: Centos 7
- Erlang/OTP: 21
- EMQ: N/A

#### Description

- X is no longer a [valid branch](https://github.com/emqx/emqx-rel/tree/X) 
- Need to update docs to point to `master` or preferred branch.

Case 
+ https://github.com/emqx/emqx-rel/blame/master/README.md#L12 
+ https://github.com/emqx/emqx-rel/blame/master/README.md#L21
+ https://github.com/emqx/emqx-rel/blame/master/README.md#L37

**Comment by HJianBo** [comment]
Hi, @TheBeachMaster I have updated these. Thanks for your feedback!
