### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by harry9932** [emqx/emqx-rel#349]
erlang   :21.2
emq      :3.1.0
os         :centos7

make[1]: 进入目录“/root/emqtt/emqx-rel/deps/emqx”
 DEP    cuttlefish
 DEP    jsx
make[2]: 进入目录“/root/emqtt/emqx-rel/.erlang.mk/rebar”
./bootstrap
/usr/bin/env: escript: 没有那个文件或目录
make[2]: *** [all] 错误 127
make[2]: 离开目录“/root/emqtt/emqx-rel/.erlang.mk/rebar”
/root/emqtt/emqx-rel/deps/emqx
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,233}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,429}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{init,start_it,1,[]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
 DEP    gproc
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,233}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,429}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{init,start_it,1,[]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
 DEP    gen_rpc
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,233}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,429}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{init,start_it,1,[]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
 DEP    ekka
 DEP    esockd
 DEP    cowboy
 DEP    replayq
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,233}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,429}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{init,start_it,1,[]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
make[2]: 进入目录“/root/emqtt/emqx-rel/deps/cuttlefish”
./rebar get-deps
/usr/bin/env: escript: 没有那个文件或目录
make[2]: *** [deps] 错误 127
make[2]: 离开目录“/root/emqtt/emqx-rel/deps/cuttlefish”
make[1]: *** [deps] 错误 2
make[1]: 离开目录“/root/emqtt/emqx-rel/deps/emqx”
make: *** [deps] 错误 2

**Comment by zhanghongtong** [comment]
If you want to build emqx v3.1.0, you can do this
```
git clone -b v3.1.0 https://github.com/emqx/emqx-rel
cd emqx-rel
export EMQX_DEPS_DEFAULT_VSN=v3.1.0
make
```
Don't forget to set the environment variable `EMQX_DEPS_DEFAULT_VSN`

**Comment by harry9932** [comment]
I tried it again according to the steps you said, but it was the same mistake.

**Comment by zhanghongtong** [comment]
You can try to build emqx in the docker container. We provide an environment image for building emqx in the docker hub, like this
```
docker pull emqx/build-env:centos7
docker run -it -e EMQX_DEPS_DEFAULT_VSN=v3.1.0 emqx/build-env:centos7 bash -c "git clone -b v3.1.0 https://github.com/emqx/emqx-rel \
&& cd emqx-rel \
&& make"
```

**Comment by harry9932** [comment]
The problem has been solved. Thank you very much.
