### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by harry9932** [emqx/emqx-rel#355]
#### Environment

- OS: centos7
- Erlang/OTP: 21.3
- EMQ: 3.1.0

./bin/emqx console
vm.args needs to have a -name parameter.
  -sname is not supported.

**Comment by wxf4150** [comment]
vm.args needs to have a -name parameter.?

i have the same issue

**Comment by wxf4150** [comment]
./_rel/emqx/bin/emqx  will ok
