### ISSUE TITLE
configure ssl for  emqx docker

### ISSUE THREAD

**Issue by 907474646** [emqx/emqx-rel#357]
#### Environment

- OS: centos
- Erlang/OTP: 21
- EMQ: v2.3.11

#### Description

I builded emqx with docker and run it ,It works well with tcp:18083 , but  encourred a error with  ssl/tcp: 8883, Maybe I did't configure the ssl with emqx docker imge,so I want to know how to configure  ssl with docker?

# ./emqtt_bench_sub  -c 1  -i 10 -t bench/%i  -h 192.168.27.129  -p 8883 -S
Topics: ["bench/%i"]
connected: 1
=INFO REPORT==== 25-May-2019::06:28:29.696566 ===
TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security

client 1 EXIT: {shutdown,
                   {tls_alert,
                       {insufficient_security,
                           "received CLIENT ALERT: Fatal - Insufficient Security"}}}

I did  all operations from  this tutorial 
![image](https://user-images.githubusercontent.com/28429514/58368423-711dc180-7f1f-11e9-97ae-5ac07e588f83.png)

![image](https://user-images.githubusercontent.com/28429514/58368363-a249c200-7f1e-11e9-9575-2a0d6fe69269.png)

**Comment by 907474646** [comment]
a trust ssl cert need to  configure for client?

**Comment by zhanghongtong** [comment]
Hi, @907474646  Sorry for the late reply

Do you resolve this problem?

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time, I will close it first, if you have any questions, you can reopen it at any time
