### ISSUE TITLE
Update plugins addition in Readme or Docs

### ISSUE THREAD

**Issue by TheBeachMaster** [emqx/emqx-rel#363]
#### Environment

- OS: Centos 7
- Erlang/OTP:  21
- EMQ: emqx-v3.0.1-114-gdabc08b

#### Description

With the new `release` update the common way of adding custom plugins has been disrupted. Initially, it involved adding `DEPS += emqx_plugin_myplugin` and `dep_emqx_plugin_myplugin = git git@vsn.org:org-namespace/my_plugin.git master` to `Makefile` and loading it inside `relx.config` as `{emqx_plugin_my_plugin, load}` 

This has been documented [here for old releases](https://developer.emqx.io/docs/broker/v3/en/plugins.html#compile-and-release-plugin); however,  the new changes  do not have this documentation. 

![Screenshot from 2019-05-27 18-41-12](https://user-images.githubusercontent.com/9129843/58429596-1b781f00-80af-11e9-9d4a-e08cd98c5012.png)

Some changes: 
![Screenshot from 2019-05-27 18-42-30](https://user-images.githubusercontent.com/9129843/58429646-3ea2ce80-80af-11e9-8ae8-e2cb63658e9c.png)

It'd be great if loading custom plugins was added to the main docs.

**Comment by TheBeachMaster** [comment]
See also #380

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
