### ISSUE TITLE
Build is failing for JSX

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx-rel#366]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 21
- EMQ: v3.2-beta.1/develop

#### Description
```
make[1]: Entering directory '/root/emqx-rel/deps/emqx'
 DEP    jsx
{"init terminating in do_boot",{{badmatch,{error,{1,erl_parse,["syntax error before: ","'.'"]}}},[{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{badmatch,{error,{1,erl_parse,[_]}}},[{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
../../erlang.mk:866: recipe for target '/root/emqx-rel/deps/jsx' failed
make[1]: *** [/root/emqx-rel/deps/jsx] Error 1
make[1]: Leaving directory '/root/emqx-rel/deps/emqx'
erlang.mk:339: recipe for target 'deps' failed
make: *** [deps] Error 2
```

I have tried `make distclean` and `make` as well but nothing works.

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
The emqx-3.2 release replaces erlang.mk with rebar3 to build the project. You should `git pull origin develop` to track the latest develop branch, install rebar3, `make distclean` and then make again. It should work.

**Comment by pritstift** [comment]
I have the same issue. @Gilbert-Wong as i understand the build process is now done differently. What are the implications regarding building EMQX with a custom plugin. [The plugin development guide](https://developer.emqx.io/docs/emq/v3/en/plugins.html#build-and-release-the-plugin) needs an update then? Can you provide some instructions on how to release a build with a custom plugin?

**Comment by Gilbert-Wong** [comment]
Yes, @pritstift this guide should be updated. Really Thanks for your feedback, we will update it as soon as possible.

**Comment by Gilbert-Wong** [comment]
And could you please open a new issue for your problem if you do not mind it?

**Comment by pritstift** [comment]
Done  #380

**Comment by Gilbert-Wong** [comment]
Thank you. I'll close this issue.
