### ISSUE TITLE
error:function_clause

### ISSUE THREAD

**Issue by harry9932** [emqx/emqx-rel#377]
#### Environment

•OS: centos7
•Erlang/OTP: 21.2
•EMQ: 3.1.0

#### Description

*A description of the issue*

(emqx@127.0.0.1)1> 2019-06-17 15:19:37.992 [error] 15588855251560755977574@192.168.1.106:49379 ** State machine <0.1752.0> terminating
** Last event = {cast,
                    {incoming,
                        {mqtt_packet,
                            {mqtt_packet_header,1,false,0,false},
                            {mqtt_packet_connect,<<"MQTT">>,4,false,true,
                                false,...},
                            undefined}}}
** When server state  = {idle,{state,esockd_transport,#Port<0.20>,
                                     {{192,168,1,...},49379},
                                     undefined,running,100,{...},...}}
** Reason for termination = error:function_clause
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{emqx_plugin_kafka,on_client_connected,
                        [#{auth_result => success,client_id => <<"1558"...>>,...},
                         0,#{...}|...],
                        [{file,...},{...}]},
     {emqx_hooks,do_run,2,[{...}|...]},
     {emqx_protocol,connack,1,[...]},
     {emqx_connection,handle_packet,3,...},
     {gen_statem,call_state_function,...}|...]

**Comment by turtleDeng** [comment]
Sorry, emqx_plugin_kafka is unofficial and cannot help you.
If you want to bridge to kafka using emqx messages, please download the emqx enterprise version on the official website https://www.emqx.io/downloads

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
