### ISSUE TITLE
Update instruction on building EMQX with custom plugins since release-3.2

### ISSUE THREAD

**Issue by pritstift** [emqx/emqx-rel#380]
#### Environment

- OS: Alpine 3.9
- Erlang/OTP: 21.3.4 
- EMQ: release-3.2

#### Description

Since the release-3.2 of EMQX rebar3 is used instead of erlang.mk for building a release. Therefore [Parts of the plugin development guide](https://developer.emqx.io/docs/emq/v3/en/plugins.html#build-and-release-the-plugin) needs an update.

**Comment by gilbertwong96** [comment]
The document has been updated now, thanks for your feedback.
