### ISSUE TITLE
startup error after build complete (release-v3.2.0)

### ISSUE THREAD

**Issue by playInfo** [emqx/emqx-rel#391]
#### Environment

- OS:  centos7.3.1611
- Erlang/OTP:  22.0
- EMQ:  release-v3.2.0

#### Description

cd emqx-rel
export EMQX_DEPS_DEFAULT_VSN=v3.2.0
make
./_build/emqx/rel/emqx/bin/emqx console

Usage: /home/emqx-rel-3.2.0/_build/emqx/rel/emqx/bin/cuttlefish
  [-h] [-e [<etc_dir>]] [-d <dest_dir>] [-f [<dest_file>]]
  [-s <schema_dir>] [-i <schema_file>] [-c <conf_file>] [-a <app_config>]
  [-l [<log_level>]] [-p] [-m [<max_history>]]

  -h, --help         Print this usage page
  -e, --etc_dir      etc dir [default: /etc]
  -d, --dest_dir     specifies the directory to write the config file to
  -f, --dest_file    the file name to write [default: app]
  -s, --schema_dir   a directory containing .schema files
  -i, --schema_file  individual schema file, will be processed in command  line order, after -s
  -c, --conf_file    a cuttlefish conf file, multiple files allowed
  -a, --app_config   the advanced erlangy app.config
  -l, --log_level    log level for cuttlefish output [default: notice]
  -p, --print        prints schema mappings on stderr
  -m, --max_history  the maximum number of generated config files to keep    [default: 3]

**Comment by turtleDeng** [comment]
Thanks for your feedback, it has been fixed in the latest version of emqx.
