### ISSUE TITLE
Building specific version?

### ISSUE THREAD

**Issue by foobarto** [emqx/emqx-rel#411]
It seems there's no way to build a specific release version currently and make/rebar are always building from `master` branches. Which is not ideal when working on a plugin for a production rollout as changes in master will quite often be breaking/becoming incompatible with stable versions. Even when checking out this repository to specific release tag the build will use `master` branch of all of the deps.

Aside from editing `rebar.config` to pin all `emqx` deps to specific release tag is there a better way or planned feature to build specific version of emqx and its plugins?

**Comment by turtleDeng** [comment]
```
git clone -b ${version} https://github.com/emqx/emqx-rel.git
```

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
