### ISSUE TITLE
How to  add external plugins

### ISSUE THREAD

**Issue by newsdy** [emqx/emqx-rel#414]
#### Environment

- OS: 
- Erlang/OTP: 21
- EMQ: v3.2.3, emqx-rel v3.2.3

#### Description

i want to add an external plugin not emqx series, How to configure it? thank you

**Comment by newsdy** [comment]
@gilbertwong96 please!  thank you!

**Comment by gilbertwong96** [comment]
Hope this [doc](https://docs.emqx.io/broker/v3/en/plugins.html#compile-and-release-plugin) could help you.

**Comment by newsdy** [comment]
> Hope this [doc](https://docs.emqx.io/broker/v3/en/plugins.html#compile-and-release-plugin) could help you.

thank you, and a hook question, in v2.3.1, the hook:
emqttd:hook('message.delivered', fun ?MODULE:on_message_delivered/4, [Env]).
but i can not find it in v3.2.3, also 'message.publish.after'
how i change them?

**Comment by gilbertwong96** [comment]
The `message.delivered` hook has been renamed as `message.deliver`.

**Comment by newsdy** [comment]
> The `message.delivered` hook has been renamed to `message.deliver`.

message.publish.after  removed?

**Comment by newsdy** [comment]
I know what the problem is. thank you

**Comment by newsdy** [comment]
@gilbertwong96 I'm sorry to disturb you again, I will upgrade the version from v2 to lastest, i found i used plugin: emq_modules in v2.  how to replace it in v3?  thanks
