### ISSUE TITLE
[Dockerfile] How to get the old version built successfully?

### ISSUE THREAD

**Issue by ozbillwang** [emqx/emqx-rel#430]
#### Environment

- OS: alpine
- Erlang/OTP: 
- EMQ: 

https://github.com/emqx/emqx-docker/blob/b2d52be0b9a044603ed16697fd1726cc2b583c27/Dockerfile

#### Description

our device doesn't support the latest version, and stay on v2.1.0 or v2.2.0

I found the old Dockerfile  (https://github.com/emqx/emqx-docker/blob/b2d52be0b9a044603ed16697fd1726cc2b583c27/Dockerfile) , but when I run the `docker build` command, I got below error: 

```
done
init terminating in do_boot ()
../../erlang.mk:810: recipe for target '/emqttd/deps/jsx' failed
make[1]: Leaving directory '/emqttd/deps/emqttd'
make[1]: *** [/emqttd/deps/jsx] Error 1
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2
```

Check https://hub.docker.com/r/emqx/emqx/tags, there is no 2.x version. 

Any suggestions?

**Comment by turtleDeng** [comment]
Sorry, emq 3.0 has been released on dockerhub, please download the old version on the official website image
https://www.emqx.io/downloads#broker

https://www.emqx.io/downloads/broker/v2.2.0/emqttd-docker-v2.2.0.zip

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close this issue.
