### ISSUE TITLE
Docker container crashes when using address type "hostname"

### ISSUE THREAD

**Issue by jcollie** [emqx/emqx-rel#442]
#### Environment

- OS: Docker
- Erlang/OTP: 22 
- EMQ: v4.0.0

#### Description

The docker container crashes when EMQX_CLUSTER__K8S__ADDRESS_TYPE is set to "hostname" but the K8S cluster has been configured for a cluster domain with something other than "cluster.local". This likely occurs because here:

https://github.com/emqx/emqx-rel/blob/master/deploy/docker/docker-entrypoint.sh#L40

it's using a fixed "cluster.local" domain to determine the Erlang hostname rather than the value of the EMQX_CLUSTER__K8S__HOSTNAME_SUFFIX or EMQX_CLUSTER__K8S__SUFFIX environment variables. Which variable you're supposed to use depends on where in the source/documentation you are reading.

**Comment by zhanghongtong** [comment]
Hi @jcollie Thanks for your feedback and we will fix this in the next release

**Comment by HJianBo** [comment]
Hi, @jcollie We have fixed and released it in v4.0.1.  Thanks for your contributions
