### ISSUE TITLE
How to terminate SSL (Port 8883) with EMQx

### ISSUE THREAD

**Issue by xforze** [emqx/emqx-rel#443]
#### Environment

- OS: Openshift 3.11
- EMQ: 3.4.5

#### Description
How can I add the Server Certificate & Key, activate and configure it in the config file ?:
```
listener.ssl.external.keyfile = etc/certs/server.key
listener.ssl.external.certfile = etc/certs/server-cert.pem
```

Are there any plans to support it via Helm Chart ?

**Comment by zhanghongtong** [comment]
Hi @xforze You can check out our [documentation](https://docs.emqx.io/broker/latest/en/guide.html#) on SSL, We plan to support configuring SSL certificates through the Helm chart in the next release, Welcome to follow us and give us start

**Comment by TheBeachMaster** [comment]
Hello @zhanghongtong the link above is dead.

**Comment by zhanghongtong** [comment]
Hi, @TheBeachMaster 
This is the address of the document: https://docs.emqx.io/broker/v3/en/guide.html#, You can also check out our [blog](https://medium.com/@emqtt/securing-emq-connections-with-ssl-432672ab9f06)

**Comment by TheBeachMaster** [comment]
@zhanghongtong  is it advisable for EMQ to handle SSL terminations?  After seeing [this](https://docs.emqx.io/broker/v3/en/deploy.html#deploying-on-private-network)
 
Asking from a production deployment point-of-view.

**Comment by zhanghongtong** [comment]
@TheBeachMaster 
It is recommended that SSL connections are terminated by a LB. The links between devices and the LB are secured by SSL, while the links between the LB and EMQ X cluster nodes are plain TCP connections. By this setup, a single EMQ X cluster can serve a million devices.

**Comment by TheBeachMaster** [comment]
Thanks @zhanghongtong
