### ISSUE TITLE
How to set/deploy horizontal pod autoscalling emqx in helm kubernetes ?

### ISSUE THREAD

**Issue by amanasmuei** [emqx/emqx-rel#453]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
How to set/deploy horizontal pod autoscalling emqx in helm kubernetes ?

**Comment by zhanghongtong** [comment]
@amanasmuei Sorry, we currently do not support set/deploy horizontal pod autoscalling emqx in helm kubernetes, perhaps you can help us to implement it

**Comment by zhanghongtong** [comment]
@amanasmuei  We recommend using statefulset to deploy EMQ X, because EMQ X is a stateful service, but statefulset doesn't support Horizontal Pod Autoscaler, so sorry

**Comment by zhanghongtong** [comment]
I will close this issue first, if you have any questions, you can open it at any time
