### ISSUE TITLE
Unable to specify settings that do not exists in the default config file when using the docker image

### ISSUE THREAD

**Issue by kblmapspeople** [emqx/emqx-rel#468]
#### Environment

- OS: ubuntu18.04
- Erlang/OTP:  R22/10.5.6
- EMQ: v4.05

#### Description

We are unable to specify any setting that does not have a default in the emqx.conf file using environmental variables. This is due to the way that the [starup script](https://github.com/emqx/emqx-rel/blob/master/deploy/docker/docker-entrypoint.sh) handles environmental variables. The startup script will read any variable starting with "EMQX_" but will only update any variable that already exist in the default emqx.conf. As a result we can for example not specify any of the settings for this feature: https://docs.emqx.io/tutorial/latest/en/bridge/emqx_to_mosquitto.html

We have tried a few workarounds for this issue with varying success.

#### 1. Mount our own emqx.conf
This approach work in docker-compose but does not work in kubernetes where we are hosting EMQX. We attempted to mount the config file using a config map and was successful. However due to the startup script writing all environmental variables into the config file the container crashes on startup as files mounted using a config map are readonly.

####  2. Build a new image with emqx/emqx:xxxx as the base
We where able to build a new image ontop of the default emqx image with the only change being that we specify a new config file. However, this approach has some not so desirable side effects. Firstly we will have to build and host a new image whenever we need to upgrade. Secondly we will have to maintain a separate config file to overwrite the default config. Any changes to the default config file will not automatically be reflected in our own config.

Is there any plan to allow all values to be configured using environmental variables so that we do not have to do these workarounds?

**Comment by zhanghongtong** [comment]
Hi, @kblmapspeople, sorry for late reply there

This issue has also troubled us for a long time, and there is no particularly good solution for the time being.

If it is deployed in kubernetes, you can mount the configuration file as configmap to pods, and then specify the command as `/usr/bin/start.sh` to skip `docker-enterpoint.sh`, like [this](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/), the disadvantage is that confmap may be very huge

We plan to divide the EMQX configuration file into user configuration and default configuration at 5.0. The user configuration can override the default configuration, which may be a good solution.

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time, I will close it first, if you have any questions, you can open it again at any time

**Comment by Airbagjoe** [comment]
Hi, @zhanghongtong 

Thank you for the reply.
We are pleased to hear that you are looking to address this issue in 5.0.

**Comment by zhanghongtong** [comment]
Welcome to watching us :)
