### ISSUE TITLE
Dependency backend_kafka is specified as a dependency but is not reachable by the system.

### ISSUE THREAD

**Issue by xiewjsir** [emqx/emqx-rel#478]
#### Environment

- OS: centos7
- Erlang/OTP: last
- EMQ: v10.7

#### Description

*A description of the issue*

Dependency backend_kafka is specified as a dependency but is not reachable by the system.

**Comment by zhanghongtong** [comment]
Hi, @xiewjsir 
Backend_kafka is a feature of our enterprise edition. The open source edition does not support it. You can get the enterprise edition installation package through [emqx.io](https://www.emqx.io/downloads#enterprise) and apply for a free license

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time, I will close it first, if you have any questions, you can open it again at any time
