### ISSUE TITLE
Missing node names on k8s

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx-rel#486]
I am missing node names on k8s. 
When selecting a node in a cluster i cant because its missing the name.
Is there a setting i forgot about in the helm chart?

i was running v.4.0.3
<img width="369" alt="missing names" src="https://user-images.githubusercontent.com/2822419/79350829-3dcd9200-7f38-11ea-9b6a-7ee78b14ced3.png">

**Comment by rjbaat** [comment]
upgraded to 4.0.5 and now i see them

**Comment by zhanghongtong** [comment]
Hi, @rjbaat 
Thanks for your feedback. Now this problem has been solved, right?

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time, I will close it first, if you have any questions, you can open it again at any time
