### ISSUE TITLE
EMQ Raspbian

### ISSUE THREAD

**Issue by a9965** [emqx/emqx-rel#501]
Hello everyone! Thanks for your help.
Is it possible to run EMQ on Raspbian? As much as I try I can not. Thank you!

**Comment by zhanghongtong** [comment]
Hi, @a9965, sorry for late reply there
EMQX supports Raspbian and you can get it at [emqx.io](https://www.emqx.io/downloads#broker)

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time, I will close it first, if you have any questions, you can open it again at any time
