### ISSUE TITLE
changing emqxConfig should signal pod restart

### ISSUE THREAD

**Issue by daadu** [emqx/emqx-rel#509]
#### Description

changing `emqxConfig` does not reload emqx as it used as ConfigMap. I would suggest using it as environment variables as it would reload the emqx

**Comment by daadu** [comment]
There are some other solution in these answer: https://stackoverflow.com/questions/37317003/restart-pods-when-configmap-updates-in-kubernetes

1. add `annotation` which is checksum of ConfigMap

**Comment by zhanghongtong** [comment]
Hi, @daadu 
Thanks for your feedback, we will try to fix it in the next version

**Comment by zhanghongtong** [comment]
Hi, @daadu
We re-evaluated this requirement, we do not intend to implement it for the time being, because restart pods are not secure in production, which may affect the business, we recommend that you use kubectl to operate the pods

```
kubectl scale statefulset/emqx --replicas=0 
kubectl scale statefulset/emqx --replicas=4
```

**Comment by zhanghongtong** [comment]
I will close this issue first, if you have any questions, you can open it at any time
