### ISSUE TITLE
emqx_auth_username and emqx_http_auth plugins

### ISSUE THREAD

**Issue by vermaabhay** [emqx/emqx-rel#522]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: 23
- EMQ: v4.0.0

#### Description

Can we not use both the plugins at the same time ?
I want few users to authenticate using emqx_auth_username plugin and the rest of the user to authenticate using emqx_http_auth. Is this possible ?

**Comment by HJianBo** [comment]
Yes,  it is.

see https://docs.emqx.io/broker/latest/en/advanced/auth.html#authentication-chain

**Comment by vermaabhay** [comment]
Thanks for the update.
