### ISSUE TITLE
emqx docker logging : log.to=console

### ISSUE THREAD

**Issue by vermaabhay** [emqx/emqx-rel#523]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 22
- EMQ: v4.0.0

#### Description
While using emqx docker image the start.sh file does a tail to erlang (in older version to emqx log file) log file. Can't we just print the logs on standard output rather in a file. 
emqx conf file has an option for log.to that can be set to "console" but since the docker image does a tail to log file, the console option can't be really used anymore. We are bound to use log.to to "file" so that start.sh can actually display logs. 

What modifications are needed in start.sh to actually print the logs on console so that log.to option to "console" actually be used in the deployment.

**Comment by zhanghongtong** [comment]
Hi, @vermaabhay Apologies for the delay

I think you misunderstood `log.to=console` will not update the `emqx.log` file, but will update the `erlang.log` file

`log.to=console` does not print the log directly to the standard output of the console

**Comment by vermaabhay** [comment]
Hi @zhanghongtong,
Is there a way we can stream the logs to standard output directly rather to a log file ?

**Comment by zhanghongtong** [comment]
Sorry, there is currently no way to do this
