### ISSUE TITLE
Hiding Secrets and Keys from logging out

### ISSUE THREAD

**Issue by daadu** [emqx/emqx-rel#524]
#### Environment

- OS: Docker
- Erlang/OTP: R22/10.7.1 
- EMQ: v4.1.0

#### Description

The `docker-entrypoint.sh` echos all environment variables to console. I am planning to use a central logging system like Loki, I dont want want the sensitive secrets like - postgres password, etc to be leaked in the logs.

One way to do it is to check for keyword `password`, `key`, `secret` or `token` before echoing it.

**Comment by daadu** [comment]
This has landed in [v4.1.1](https://github.com/emqx/emqx/releases/tag/v4.1.1). Hence closing it

**Comment by daadu** [comment]
@zhanghongtong Do you think we should provide additional env that describes configs to be masked/hiden.

Something like
```
MASK_CONFIG=auth.pgsql.password,auth.auth.pgsql.username
```

The current implementation does not work, when I have sensitive values in config that does not have pre-defined keywords.

For eg: in emqx_web_hook i am setting basic auth params like following:
```
 EMQX_WEB__HOOK__API__URL: http://emqx-webhook:password@localhost/mqtt/webhook/
```

**Comment by daadu** [comment]
Or we should simply not echo any env

**Comment by zhanghongtong** [comment]
Hi, @daadu I think this is a good idea
I think we can provide the default `MASK_CONFIG`, just like `password | passwd | key |secret | token`, if the user sets a new `MASK_CONFIG`, then the values ​​of these two variables will be merged

**Comment by daadu** [comment]
I think merging would be bad idea, instead we should just either use default or user defined.

**Comment by daadu** [comment]
@zhanghongtong Added this enhancement in #547 along with documentation. Please review it.
