### ISSUE TITLE
_checkouts/pbkdf2/src/pbkdf2.erl failed

### ISSUE THREAD

**Issue by WalidMafuj** [emqx/emqx-rel#533]
#### Environment

- OS:  Raspberry pi OS [ on raspberry pi 3 armhf ]
- Erlang/OTP: 23
- EMQ: v4.0.10

#### Description

*A description of the issue*
Tried several times to build from source but its showing  same error:

===>Verifying dependencies...
===> Compiling jsx
===> Compiling coveralls
===> "/etc/emqx-rel/_checkouts/mysql/ebin/mysql.app" is missing kernel from applications list
===> "/etc/emqx-rel/_checkouts/mysql/ebin/mysql.app" is missing stdlib from applications list
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> "/etc/emqx-rel/_checkouts/ssl_verify_fun/ebin/ssl_verify_fun.app" is missing description entry
===> Compiling gen_coap
===> Compiling jsx
===> Compiling gproc
===> Compiling ssl_verify_fun
===> "/etc/emqx-rel/_checkouts/ssl_verify_fun/ebin/ssl_verify_fun.app" is missing description entry
===> Compiling gen_rpc
===> Compiling esockd
===> Compiling ekka
===> Compiling getopt
===> Compiling cuttlefish
===> Running neotoma...
make[1]: Entering directory '/etc/emqx-rel/_build/emqx/lib/cuttlefish'
/etc/emqx-rel/_build/emqx/lib/cuttlefish/rebar3 as escript escriptize
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...
===> Compiling cuttlefish
===> Running neotoma...
===> Building escript...
make[1]: Leaving directory '/etc/emqx-rel/_build/emqx/lib/cuttlefish'
===> Compiling ranch
===> Compiling cowlib
===> Compiling cowboy
===> Compiling emqx
===> Compiling emqx_coap
===> Compiling jpparse
===> Compiling sqlparse
===> Compiling minirest
===> Compiling emqx_rule_engine
===> Compiling emqx_reloader
===> Compiling emqx_management
===> Compiling emqx_dashboard
===> Compiling lwm2m_coap
===> Compiling bcrypt
===> Compiling c_src/async_queue.c
===> Compiling c_src/bcrypt.c
===> Compiling c_src/bcrypt_nif.c
===> Compiling c_src/bcrypt_port.c
===> Compiling c_src/blowfish.c
===> Compiling ecpool
===> Compiling mysql
===> "/etc/emqx-rel/_checkouts/mysql/ebin/mysql.app" is missing kernel from applications list
===> "/etc/emqx-rel/_checkouts/mysql/ebin/mysql.app" is missing stdlib from applications list
===> Compiling poolboy
===> Compiling pbkdf2
===> **Compiling _checkouts/pbkdf2/src/pbkdf2.erl failed**
_checkouts/pbkdf2/src/pbkdf2.erl:113: crypto:hmac_init/2 is deprecated and will be removed in OTP 24; use use crypto:mac_init/3 instead
_checkouts/pbkdf2/src/pbkdf2.erl:114: crypto:hmac_update/2 is deprecated and will be removed in OTP 24; use use crypto:mac_update/2 instead
_checkouts/pbkdf2/src/pbkdf2.erl:115: crypto:hmac_final/1 is deprecated and will be removed in OTP 24; use use crypto:mac_final/1 instead

**make: *** [Makefile:51: emqx] Error 1**

**Comment by HJianBo** [comment]
We will fix it later. Now you should use the OTP22 to compile it

**Comment by HJianBo** [comment]
Fixed v4.2-rc.1

**Comment by WalidMafuj** [comment]
Thank you
