### ISSUE TITLE
Loaded Modules Docker Support in 4.1.0

### ISSUE THREAD

**Issue by louisburton** [emqx/emqx-rel#535]
#### Environment

- OS: EMQ X Docker
- EMQ: 4.1.0

#### Description

4.1.0 has made a breaking change to shift from turning on modules in emqx.conf to a loaded_modules file that mirrors the loaded_plugins. 
https://github.com/emqx/emqx/pull/3376

(Despite the file essentially being a list of what is turned on, with no false values there by default, it has deviated from the loaded_plugins format - which seems inconsistent to me)

Unfortunately, since this change, I do not see a way of currently overriding the loaded modules in the Dockerfile, and it appears to regress the ability to start the container with a module like `rewrite` turned on.
Now that it mirrors the loaded_plugins approach so closely, I would have expected a similar mechanism to the EMQX_LOADED_PLUGINS environment variable support seen here:
https://github.com/emqx/emqx-rel/blob/master/deploy/docker/docker-entrypoint.sh#L146-L154

Perhaps something equivalent like this:
```
## EMQ Module load settings
# Modules loaded by default

if [[ ! -z "$EMQX_LOADED_MODULES" ]]; then
    echo "EMQX_LOADED_MODULES=$EMQX_LOADED_MODULES"
    echo $(echo "$EMQX_LOADED_MODULES"|sed -e "s/^[^A-Za-z0-9_]\{1,\}//g"|sed -E "s/([^,]*),*/{\1, true}./g"|sed -e "s/}.{/}.\${/g")|tr '$' '\n' > /opt/emqx/data/loaded_modules
fi
```

**Comment by zhanghongtong** [comment]
Hi, @louisburton 
Thank you for your suggestion. We will implement it in later versions

**Comment by louisburton** [comment]
Good to know. Thanks for responding so quickly 👍

**Comment by zhanghongtong** [comment]
You're welcome :)

**Comment by alexandrim0** [comment]
Hi!

With this changes EMQX_LOADED_PLUGINS is broken now.
Good if I can configure with file but no good if I can not configure with env var.

Guess, env var still should be able to overwrite any file config.
Guess, a new config param for new feature and using of EMQX_LOADED_PLUGINS like before is a good way.

**Comment by zeroallox** [comment]
I have run into this issue as well while using docker-compose

If i specify:

```
    - "EMQX_LOADED_PLUGINS=emqx_management,emqx_auth_redis,emqx_recon,emqx_retainer,emqx_dashboard"
```

I get the following crash:

```
node.max_ports=1048576
zone.internal.max_awaiting_rel=0
auth.redis.server=redis.app.internal
listener.tcp.external.acceptors=64
zone.external.max_awaiting_rel=0
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
zone.external.max_packet_size=10MB
cluster.discovery=static
cluster.discovery=static
listener.ws.external.acceptors=16
zone.internal.max_mqueue_len=0
zone.external.max_mqueue_len=0
cluster.static.seeds=emqx@mq1.app.internal,emqx@mq2.app.internal
cluster.static.seeds=emqx@mq1.app.internal,emqx@mq2.app.internal
EMQX_LOADED_PLUGINS=emqx_management,emqx_auth_redis,emqx_recon,emqx_retainer,emqx_dashboard
EMQ X Broker v4.1.1 is started successfully!
                                                         ["syntax error before: ",
                                                          "'.'"]}
Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.1.1 is running now!
Eshell V10.7.1  (abort with ^G)
(emqx@mq1.app.internal)1> ['2020-07-03T20:19:38Z']:emqx start
['2020-07-03T20:19:38Z']:emqx not running, waiting for recovery in 20 seconds
```

**Comment by zhanghongtong** [comment]
Hi, @zeroallox @alexandrim0 
Thanks for reminding, this is our mistake, we have hot fixed this error, you can re-pull the `emqx/emqx:v4.1.1` image and try again

**Comment by alexandrim0** [comment]
Now it works fine for me.
Thank you!

**Comment by louisburton** [comment]
I don't think this is working correctly for `EMQX_LOADED_MODULES` in `v4.1.1`.
Have added a couple of comments to the original PR.
