### ISSUE TITLE
helm charts do not work in alibaba cloud

### ISSUE THREAD

**Issue by kai8406** [emqx/emqx-rel#549]
#### Environment

- Kubernetes Version: k8s v 1.12
- Storage class Name：alicloud-disk-efficiency
- Chart Version:  v4.1.1

#### Description
when i execute helm command：
`helm install mqtt-broker emqx/emqx --set persistence.enabled=true --set persistence.storageClass=alicloud-disk-efficiency --set persistence.size=20Gi -n mqtt`

pvc log is
  `Warning  ProvisioningFailed    2m51s                 alicloud/disk alicloud-disk-controller-xxxxxx-xxxxx xxxxx-xxxx-xxxx-xxxx-xxxxxxxx  Failed to provision volume with StorageClass "alicloud-disk-efficiency": Aliyun API Error: RequestId: xxxxxxxx-xxxxxx-xxx-xxxx-xxxxxxxx Status Code: 400 Code: InvalidParameter Message: The specified parameter "Size" is not valid.`

The `persistence.size` parameter doesn't seem to work.

**Comment by zhanghongtong** [comment]
Hi, @kai8406 
I think this may be caused by your version of k8s is too low.
The Local Persistent Volumes feature has been promoted to GA in Kubernetes 1.14.

**Comment by kai8406** [comment]
> Hi, @kai8406
> I think this may be caused by your version of k8s is too low.
> The Local Persistent Volumes feature has been promoted to GA in Kubernetes 1.14.
> Maybe you can upgrade the k8s cluster and try again

Thank you for your answer.
The PVC Disk must be Local Persistent Volumes？
I think the message on the broker does not need the high IO of the local disk on the cloud.
Considering scalability and cost,I suggest to support general cloud disk.

**Comment by zhanghongtong** [comment]
Hi, @kai8406 
The location of the PVC disk depends on your PV resources or StorageClass resources. StorageClass resources provide cloud vendor plug-ins, similar to AWS EBS or Azure Disk, you can view the [kubernetes documentation](https://kubernetes.io/docs/concepts/storage/)
