### ISSUE TITLE
EMQX stops printing logs to console after a while

### ISSUE THREAD

**Issue by sgrigorev** [emqx/emqx-rel#552]
#### Environment

I run emqx/emqx:v4.1.0 docker image on Kubernetes.

#### Description

I was testing of EMQX and noticed that it stops printing logs to stdout after a while. The problem is reproduced if many clients are connected to EMQX and send messages (I had about 3000 mqtt connections). At the moment, EMQX works for two days with one mqtt connection and the printing of logs has not stopped. Therefore, I think that the issue happens only under load. 

Inside the container I see the following log files: erlang.log.1, erlang.log.2, erlang.log.3, erlang.log.4, run_erl.log.
Log level is set to debug and log.to is set to console.

**Comment by zhanghongtong** [comment]
Hi, @sgrigorev 
Sorry, this is our oversight, we will fix it in the next version

**Comment by sgrigorev** [comment]
@zhanghongtong when do you plan to release the new version?

**Comment by zhanghongtong** [comment]
CC @tigercl 
When do we plan to release 4.1.2?

**Comment by zhanghongtong** [comment]
Hi, @sgrigorev 
We have released 4.1.2, welcome to use :)

**Comment by sgrigorev** [comment]
@zhanghongtong Thanks a lot!

**Comment by zhanghongtong** [comment]
@sgrigorev You're welcome :)
