### ISSUE TITLE
EMQ X Broker v4.1.1 fails to start

### ISSUE THREAD

**Issue by dsilletti** [emqx/emqx-rel#553]
#### Environment

- OS: Ubuntu 20.04
- Docker: 19.03.12
- EMQ: 4.1.1

#### Description

EMQ X Broker v4.1.1 fails to start. No issues running EMQ X Broker v4.1.0 with the same config.

mqtt-broker        | node.max_ports=1048576
mqtt-broker        | mqtt.retain_available=false
mqtt-broker        | dashboard.default_user.password=***secret***
mqtt-broker        | listener.tcp.external.acceptors=64
mqtt-broker        | acl_nomatch=deny
mqtt-broker        | zone.external.enable_acl=on
mqtt-broker        | mqtt.max_packet_size=1KB
mqtt-broker        | dashboard.default_user.login=admin
mqtt-broker        | listener.ws.external.rate_limit=500KB,1m
mqtt-broker        | listener.ws.external=8080
mqtt-broker        | mqtt.max_qos_allowed=0
mqtt-broker        | allow_anonymous=false
mqtt-broker        | mqtt.max_clientid_len=256
mqtt-broker        | listener.ssl.external.acceptors=32
mqtt-broker        | node.process_limit=2097152
mqtt-broker        | node.max_ets_tables=2097152
mqtt-broker        | listener.ws.external.acceptors=16
mqtt-broker        | listener.tcp.external.rate_limit=500KB,1m
mqtt-broker        | acl_file=etc/acl.conf
mqtt-broker        | listener.tcp.external=1883
mqtt-broker        | acl_deny_action=disconnect
mqtt-broker        | EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
mqtt-broker        | EMQ X Broker v4.1.1 failed to start within 15 seconds,
mqtt-broker        | see the output of '/opt/emqx/bin/emqx console' for more information.
mqtt-broker        | If you want to wait longer, set the environment variable
mqtt-broker        | WAIT_FOR_ERLANG to the number of seconds to wait.
mqtt-broker        | 
mqtt-broker        | =====
mqtt-broker        | ===== LOGGING STARTED Wed Jul 15 22:59:17 UTC 2020
mqtt-broker        | =====
mqtt-broker        | Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.1/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesia/emqx@172.19.0.10" -config /opt/emqx/data/configs/app.2020.07.15.22.59.17.config -args_file /opt/emqx/data/configs/vm.2020.07.15.22.59.17.args -vm_args /opt/emqx/data/configs/vm.2020.07.15.22.59.17.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
mqtt-broker        | Root: /opt/emqx
mqtt-broker        | /opt/emqx
mqtt-broker        | {"init terminating in do_boot",{load_failed,[emqx_stats,emqx_zone,emqx_vm_mon,emqx_vm,emqx_tracer,emqx_tables,emqx_sys_mon,emqx_ws_connection,emqx_sys,emqx_types,emqx_topic,emqx_trie,emqx_sup,emqx_sys_sup,emqx,emqx_sequence,emqx_shared_sub,emqx_session,emqx_router_sup,emqx_router,emqx_reason_codes,emqx_psk,emqx_pqueue,emqx_pool_sup,emqx_pmon,emqx_pool,emqx_plugins,emqx_pd,emqx_mountpoint,emqx_mqtt_props,emqx_rpc,emqx_router_helper,emqx_mod_topic_metrics,emqx_modules,emqx_mod_sup,emqx_mod_subscription,emqx_os_mon,emqx_packet,emqx_mqueue,emqx_mqtt_caps,emqx_mod_presence,emqx_mod_rewrite,emqx_mod_delayed,emqx_misc,emqx_mod_acl_internal,emqx_metrics,emqx_message,emqx_logger_formatter,emqx_listeners,emqx_logger,emqx_limiter,emqx_keepalive,emqx_kernel_sup,emqx_json,emqx_inflight,emqx_hooks,emqx_guid,emqx_global_gc,emqx_gen_mod,emqx_gc,emqx_frame,emqx_flapping,emqx_ctl,emqx_connection,emqx_cm_sup,emqx_cm_registry,emqx_cm,emqx_broker_helper,emqx_broker,emqx_acl_cache,emqx_boot,emqx_batch,emqx_cm_locker,emqx_channel,emqx_alarm_handler,emqx_broker_sup,emqx_access_rule,emqx_access_control,emqx_banned,emqx_base62,emqx_app]}}
mqtt-broker        | init terminating in do_boot ({load_failed,[emqx_stats,emqx_zone,emqx_vm_mon,emqx_vm,emqx_tracer,emqx_tables,emqx_sys_mon,emqx_ws_connection,emqx_sys,emqx_types,emqx_topic,emqx_trie,emqx_sup,emqx_sys_s
mqtt-broker        | 
mqtt-broker        | Crash dump is being written to: log/crash.dump...done
mqtt-broker        | ['2020-07-15T22:59:37Z']:emqx exit abnormally
mqtt-broker exited with code 1

**Comment by zhanghongtong** [comment]
Hi, @dsilletti 
Are you using the docker image you built yourself?

**Comment by dsilletti** [comment]
Hi @zhanghongtong 
I am using the official docker image, I never had issues with previous releases.

**Comment by zhanghongtong** [comment]
@dsilletti I tried to run it, it is normal
Can you share your `docker run` command?

**Comment by dsilletti** [comment]
@zhanghongtong please find my docker-compose file content below:

  mqtt-broker:
    image: emqx/emqx:v4.1.1
    restart: always
    container_name: mqtt-broker
    environment:
      - EMQX_NAME=emqx
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LISTENER__WS__EXTERNAL=8080
      - EMQX_acl_nomatch=deny
      - EMQX_zone__external__enable_acl=on
      - EMQX_acl_file=etc/acl.conf
      - EMQX_acl_deny_action=disconnect
      - EMQX_MQTT__MAX_PACKET_SIZE=1KB
      - EMQX_mqtt__max_clientid_len=256
      - EMQX_mqtt__max_qos_allowed=0
      - EMQX_mqtt__retain_available=false
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_dashboard__default_user__login=admin
      - EMQX_dashboard__default_user__password=SECRET
      - EMQX_zone__external__publish_limit=500,1m
      - EMQX_listener__tcp__external__rate_limit=500KB,1m
      - EMQX_listener__ws__external__rate_limit=500KB,1m
    volumes:
      - ./emqx/etc/acl.conf:/opt/emqx/etc/acl.conf
      - ./emqx/etc/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
    logging:
      options:
        max-size: "200k"
        max-file: "10"

**Comment by dsilletti** [comment]
changing the image to: emqx/emqx:v4.1.0 works with no issues:

mqtt-broker        | zone.external.publish_limit=500,1m
mqtt-broker        | node.max_ports=1048576
mqtt-broker        | mqtt.retain_available=false
mqtt-broker        | dashboard.default_user.password=SECRET
mqtt-broker        | listener.tcp.external.acceptors=64
mqtt-broker        | acl_nomatch=deny
mqtt-broker        | zone.external.enable_acl=on
mqtt-broker        | mqtt.max_packet_size=1KB
mqtt-broker        | dashboard.default_user.login=admin
mqtt-broker        | listener.ws.external.rate_limit=500KB,1m
mqtt-broker        | listener.ws.external=8080
mqtt-broker        | mqtt.max_qos_allowed=0
mqtt-broker        | allow_anonymous=false
mqtt-broker        | mqtt.max_clientid_len=256
mqtt-broker        | listener.ssl.external.acceptors=32
mqtt-broker        | node.process_limit=2097152
mqtt-broker        | node.max_ets_tables=2097152
mqtt-broker        | listener.ws.external.acceptors=16
mqtt-broker        | listener.tcp.external.rate_limit=500KB,1m
mqtt-broker        | acl_file=etc/acl.conf
mqtt-broker        | listener.tcp.external=1883
mqtt-broker        | acl_deny_action=disconnect
mqtt-broker        | EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
mqtt-broker        | EMQ X Broker v4.1.0 is started successfully!
mqtt-broker        | /opt/emqx
mqtt-broker        | Starting emqx on node emqx@172.19.0.6
mqtt-broker        | Start http:management listener on 8081 successfully.
mqtt-broker        | Start http:dashboard listener on 18083 successfully.
mqtt-broker        | Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
mqtt-broker        | Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
mqtt-broker        | Start mqtt:ws listener on 0.0.0.0:8080 successfully.
mqtt-broker        | EMQ X Broker 4.1.0 is running now!
mqtt-broker        | Eshell V10.7.1  (abort with ^G)
mqtt-broker        | (emqx@172.19.0.6)1> ['2020-07-16T11:11:03Z']:emqx start

**Comment by zhanghongtong** [comment]
Hi, @dsilletti 
I use the docker-compose file you provided to run normally
Can you check the sha256 value of the image through the `docker image inspect emqx/emqx:v4.1.1` ?

**Comment by dsilletti** [comment]
Hi @zhanghongtong,
probably something was wrong with docker, rebooting Ubuntu solved the problem, EMQ X Broker 4.1.1 is now up and running.
Thanks for your support

**Comment by zhanghongtong** [comment]
@dsilletti You're welcome :)
