### ISSUE TITLE
How multiple java clients can jointly consume a topic or topic group?

### ISSUE THREAD

**Issue by trollhe** [emqx/emqx-rel#563]
#### Environment

- OS: Centos 7.6.1810
- EMQ:  

#### Description

多个java客户端如何消费用一个topic？
创建resut/1,result/2,reult/3这3个topic,创建10个client，当客户端clientid相同时，只能有1个客户端消费或者初始化成功；当每个客户端clientid不同时，存在1条消息被消费10次的情况；
我的诉求是10个客户端共同消费一个topic组result/#,不能重复消费;但官方没有这方面的说明，希望能够提供demo代码或者文档链接，谢谢。

**Comment by HJianBo** [comment]
see: https://docs.emqx.io/broker/latest/en/advanced/proxy-subscriptions.html

**Comment by 907474646** [comment]
the only method is to save topic messages to&nbsp; other mq


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emqx/emqx-rel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 下午4:58
收件人:&nbsp;"emqx/emqx-rel"<emqx-rel@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[emqx/emqx-rel] 多个java客户端如何共同消费一个topic或者topic组？ (#563)





 
Environment
  
OS: Centos 7.6.1810
 
EMQ:
  
Description
 
多个java客户端如何消费用一个topic？
 创建resut/1,result/2,reult/3这3个topic,创建10个client，当客户端clientid相同时，只能有1个客户端消费或者初始化成功；当每个客户端clientid不同时，存在1条消息被消费10次的情况；
 我的诉求是10个客户端共同消费一个topic组result/#,不能重复消费;但官方没有这方面的说明，希望能够提供demo代码或者文档链接，谢谢。
