### ISSUE TITLE
Helm upgrade doesn't change emqxConfig settings

### ISSUE THREAD

**Issue by dsarosi** [emqx/emqx-rel#564]
#### Kubernetes

- EMQ: 4.1.1

#### Description

I'm trying to change the allow.anonymous setting using a helm upgrade.  In my values.yaml, I use the following setting.

```
emqxConfig:
  EMQX_ALLOW_ANONYMOUS: false
```

When using helm install it all works fine, but if I change the setting and do a helm upgrade then no change takes place for the cluster.

**Comment by zhanghongtong** [comment]
Hi, @dsarosi 
Sorry, `emqxConfig` is configured as a `ConfigMap` in the emqx chart, and then the `Pod` is introduced through environment variables. When the `ConfigMap` is updated, the environment variables of the `Pod` will not be updated at the same time.
