### ISSUE TITLE
EMQX_MQTT__MAX_PACKET_SIZE  set failed

### ISSUE THREAD

**Issue by moluzhui** [emqx/emqx-rel#569]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ:   emqx/emqx:v4.1.1

#### Description

*A description of the issue*
I modified EMQx's `mqtt.max_packet_size` configuration for the supported payload size based on [EMQX Docker Hub](https://hub.docker.com/r/emqx/emqx) using the following command
```

docker run -d  -p 1883:1883 -e EMQX_MQTT__MAX_PACKET_SIZE=5M emqx/emqx:v4.1.1
```

 but the following error occurred
```
$ docker logs -f emqx_broker
node.max_ports=1048576
listener.tcp.external.acceptors=64
mqtt.max_packet_size=5M
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
listener.ws.external.acceptors=16
EMQ X Broker v4.1.1 failed to start within 15 seconds,
see the output of '/opt/emqx/bin/emqx console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

=====
===== LOGGING STARTED Sat Aug  8 01:00:46 UTC 2020
=====
2020-08-08T01:00:47.915554+00:00 [error] Error generating configuration in phase transform_datatypes
2020-08-08T01:00:47.915680+00:00 [error] Error transforming datatype for: mqtt.max_packet_size
['2020-08-08T01:01:12Z']:emqx exit abnormally
```

Have you changed the configuration method?

**Comment by zhanghongtong** [comment]
Hi, @moluzhui 
You need to set `EMQX_MQTT__MAX_PACKET_SIZE=5MB` instead of `EMQX_MQTT__MAX_PACKET_SIZE=5M`

**Comment by moluzhui** [comment]
> Hi, @moluzhui
> You need to set `EMQX_MQTT__MAX_PACKET_SIZE=5MB` instead of `EMQX_MQTT__MAX_PACKET_SIZE=5M`

HI, @zhanghongtong 
I'm sorry, it was an oversight.
Ask if 1M is the default optimal value and if I change it to 5MB, do I need to change other configurations to match it?

**Comment by zhanghongtong** [comment]
@moluzhui 
mqtt.max_packet_size determines the maximum packet size accepted by EMQX, It has no so-called optimal value, it should be determined by your business

**Comment by moluzhui** [comment]
> @moluzhui
> mqtt.max_packet_size determines the maximum packet size accepted by EMQX, It has no so-called optimal value, it should be determined by your business
