### ISSUE TITLE
new emqx docker image with custom plugin

### ISSUE THREAD

**Issue by lucafolin** [emqx/emqx-rel#570]
Hi, I would like to customize this emqx plugin "emqx_plugin_template" and use emqx in a docker container.
Please could you guide me to perfome a new emqx docker image with custom plugin ?

**Comment by zhanghongtong** [comment]
Hi, @lucafolin 
It is recommended that you mount `etc/plugins/emqx_plugin_template.config` on the host machine and enable the `emqx_plugin_template` plugin by setting the environment variable `EMQX_LOADED_PLUGINS`

**Comment by lucafolin** [comment]
HI zhanghongtong, thk for your answare. My problem is that I need to build a new pluign using "emqx_plugin_template" so I need to compile new version of EMQX brocker and then I don't know how to perform this new docker's image. Could you guide me trought the first steps on how to obtain new docker image with customized plugin? Are there other ways to run EMQX docker with customized plugin ?

**Comment by zhanghongtong** [comment]
Hi, @lucafolin 
If you want to put your own code in the image of emqx, you can only compile the emqx image from the code.
Get the code of [emqx/emqx-rel](https://github.com/emqx/emqx-rel), and switch the tag to the version number you want, modify `rebar.config` to ensure that it can pull your plugin as a dependency, and run `make emqx-docker-build`

**Comment by lucafolin** [comment]
Hi @zhanghongtong I have modified my custom plugin and then I recompiled all the code at the end  emqx with my custom plugin works fine.
When I try to recompile the code for a docker image with this command line "cd emqx-rel && make emqx-docker-build"  I receive many allert like this:

 Compiling xxxxxxxx
===> Failed to restore /emqx_rel/_checkouts/xxxxxxxx/.rebar3/rebar_compiler_erl/source.dag file. Discarding it.

The image was successfully created in any case. But when I try to start the container it doesn't work. Could you help me bulding docker image ? Why I receive these compiling error ?

**Comment by zhanghongtong** [comment]
Hi, @lucafolin 
Can you provide a log of running the container useing you docker image

**Comment by lucafolin** [comment]
HI @zhanghongtong this is my container log:

`{"log":"node.max_ports=1048576\n","stream":"stdout","time":"2020-08-13T12:57:06.430829392Z"}
{"log":"listener.tcp.external.acceptors=64\n","stream":"stdout","time":"2020-08-13T12:57:06.784303996Z"}
{"log":"listener.ssl.external.acceptors=32\n","stream":"stdout","time":"2020-08-13T12:57:07.423468869Z"}
{"log":"node.process_limit=2097152\n","stream":"stdout","time":"2020-08-13T12:57:07.578506064Z"}
{"log":"node.max_ets_tables=2097152\n","stream":"stdout","time":"2020-08-13T12:57:07.731721983Z"}
{"log":"listener.ws.external.acceptors=16\n","stream":"stdout","time":"2020-08-13T12:57:07.907415407Z"}
{"log":"node.name=ca05bd1a2bb1@172.17.0.2\n","stream":"stdout","time":"2020-08-13T12:57:08.077496857Z"}
{"log":"\n","stream":"stdout","time":"2020-08-13T12:58:27.258618621Z"}
{"log":"=====\n","stream":"stdout","time":"2020-08-13T12:58:27.258686859Z"}
{"log":"===== LOGGING STARTED Thu Aug 13 12:57:14 UTC 2020\n","stream":"stdout","time":"2020-08-13T12:58:27.258709422Z"}
{"log":"=====\n","stream":"stdout","time":"2020-08-13T12:58:27.258730222Z"}
{"log":"Exec: /opt/emqx/erts-10.5.6/bin/erlexec -boot /opt/emqx/releases/v4.0.0/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.5.6/../lib -mnesia dir \"/opt/emqx/data/mnesia/ca05bd1a2bb1@172.17.0.2\" -config /opt/emqx/data/configs/app.2020.08.13.12.57.24.config -args_file /opt/emqx/data/configs/vm.2020.08.13.12.57.24.args -vm_args /opt/emqx/data/configs/vm.2020.08.13.12.57.24.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console\r\n","stream":"stdout","time":"2020-08-13T12:58:27.25875181Z"}
{"log":"Root: /opt/emqx\r\n","stream":"stdout","time":"2020-08-13T12:58:27.25877786Z"}
{"log":"/opt/emqx\r\n","stream":"stdout","time":"2020-08-13T12:58:27.258798298Z"}
{"log":"{\"Kernel pid terminated\",application_controller,\"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,bcrypt_nif}}},{kernel,start,[normal,[]]}}}\"}\r\r\n","stream":"stdout","time":"2020-08-13T12:58:27.258818973Z"}
{"log":"Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,bcrypt_nif}}},{kernel,start,[normal,[]]}}})\r\r\n","stream":"stdout","time":"2020-08-13T12:58:27.258840511Z"}
{"log":"\r\r\n","stream":"stdout","time":"2020-08-13T12:58:27.258861786Z"}
{"log":"Crash dump is being written to: log/crash.dump...done\r\r\n","stream":"stdout","time":"2020-08-13T12:58:27.258881961Z"}
{"log":"['2020-08-13T12:58:27Z']:emqx exit abnormally\n","stream":"stdout","time":"2020-08-13T12:58:27.261082319Z"}

after few minutes the container ends up.
`

**Comment by zhanghongtong** [comment]
Hi, @lucafolin 
Before executing `make emqx-docker-build`, you need to execute `make distclean` to ensure that the code directory is clean.

**Comment by lucafolin** [comment]
Hi @zhanghongtong if I make a `make distclean` the doker works but I lost the customozation of the `emqx_plugin_template` that I made. In this way I have a "standard" emqx doker running. On an Ubuntu emqx installation I usually modify `emqx-rel/_build/emqx/lib/emqx_plugin_template/src/emqx_plugin_template.erl`  and than I recompile the code and my custom plugin works fine.
What I wolud like to achive now is to run an emqx docker installation with this customized plugin. If I make a `make distclean` I lost my customization code. How can I go on on my project ?

**Comment by zhanghongtong** [comment]
@lucafolin 
Try to use `make distclean && make deps-emqx` to pull all dependencies, modify your code and execute `make emqx-docker-build`, and ensure that the `_build/emqx/rel` directory does not exist before execute `make emqx-docker-build`

**Comment by lucafolin** [comment]
Hi @zhanghongtong thk for your help. Now I'm able to build the emqx docker container and the customized plugin works, but in the docker logs I receive an error as you can see in the attached file when I start sending mqtt message. Can you help me to understand how to fix it ?

[error_emqx.txt](https://github.com/emqx/emqx-rel/files/5078270/error_emqx.txt)

**Comment by lucafolin** [comment]
ok @zhanghongtong I fix the problem. It's only a mistake in emqx_plugin_template.erl code that I have inserted when I have customized the plugin. I have rebuilded the plugin from the oroginal file and it works fine.
Now how can I make "emqx_plugin_tempalte" starts automatically  when emqx starts runngin ?

**Comment by zhanghongtong** [comment]
Hi, @lucafolin 
Apologies for the delay
You can start the plugin through [environment variables](https://github.com/emqx/emqx-rel/tree/master/deploy/docker#emq-loaded-plugins-configuration)
