### ISSUE TITLE
EMQ X Broker v4.2.x failed to build

### ISSUE THREAD

**Issue by juexun** [emqx/emqx-rel#604]
#### Environment

- OS: macos 10.15.7
- Erlang/OTP: 21.3.8.18
- EMQ: 4.2.0/1/2

#### Description

Install from source:

`
$ git clone -b v4.2.2 https://github.com/emqx/emqx-rel.git emqx-4.2.2
$ cd emqx-4.2.2
$ export EMQX_DEPS_DEFAULT_VSN=v4.2.2
$ make
`

I failed with the following output:
`
export EMQX_DESC="EMQ X Broker"
/Users/eamon/dev/emqx-4.2.2/rebar3 as emqx release
===> Error evaluating configuration script at "rebar.config.script":
{error,{217,file,
        {error,badarg,
               [{re,run,
                    [[40,38750,20998,25903,41],
                     "master|^dev/|^hotfix/",
                     [{capture,none}]],
                    []},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,273}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,449}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},
                {file,eval_stream2,6,[{file,"file.erl"},{line,1393}]},
                {file,script,2,[{file,"file.erl"},{line,1090}]},
                {rebar_config,consult_and_eval,2,
                              [{file,"/Users/emqer/code/rebar3/src/rebar_config.erl"},
                               {line,287}]}]}}}

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [emqx] Error 1
`

**Comment by zhanghongtong** [comment]
Hi, @juexun 
Please add `ct:print("==================~p~n",[CONFIG4]),` to line 215 of `rebar.config.script` and tell us the printed result

**Comment by juexun** [comment]
(base) ➜  emqx-4.2.2 git:(4b85617) ✗ make
export EMQX_DESC="EMQ X Broker"
/Users/eamon/dev/emqx-4.2.2/rebar3 as emqx release
===> Error evaluating configuration script at "rebar.config.script":
{error,{217,file,
        {error,badarg,
               [{re,run,
                    [[40,38750,20998,25903,41],
                     "master|^dev/|^hotfix/",
                     [{capture,none}]],
                    []},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,273}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,449}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},
                {file,eval_stream2,6,[{file,"file.erl"},{line,1393}]},
                {file,script,2,[{file,"file.erl"},{line,1090}]},
                {rebar_config,consult_and_eval,2,
                              [{file,"/Users/emqer/code/rebar3/src/rebar_config.erl"},
                               {line,287}]}]}}}

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [emqx] Error 1

**Comment by zhanghongtong** [comment]
Did you add the command to the right place? I don’t see what is printed

**Comment by juexun** [comment]
214 file:write_file(FilePath, [io_lib:format("~p.\n", [I]) || I <- CONFIG4]),
215 ct:print("==================~p~n",[CONFIG4]),
216 CONFIG4.

**Comment by zhanghongtong** [comment]
@juexun 
Change line 111 of rebar.config.script to the following:

```
GitRef = case re:run(unicode:characters_to_binary(Branch), "master|^dev/|^hotfix/", [{capture, none}]) of
```

**Comment by juexun** [comment]
....
===> Compiling rebar3_proper
===> Fetching emqx_auth_clientid (from {git,"https://github.com/emqx/emqx-auth-clientid",
                              {tag,"v4.2.2"}})
===> Error evaluating configuration script at "/Users/eamon/dev/emqx-4.2.2/_build/emqx/lib/emqx_auth_clientid/rebar.config.script":
{error,{55,file,
        {error,badarg,
               [{re,run,
                    [[40,38750,20998,25903,41],
                     "master|^dev/|^hotfix/",
                     [{capture,none}]],
                    []},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,273}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,449}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},
                {file,eval_stream2,6,[{file,"file.erl"},{line,1393}]},
                {file,script,2,[{file,"file.erl"},{line,1090}]},
                {rebar_config,consult_and_eval,2,
                              [{file,"/Users/emqer/code/rebar3/src/rebar_config.erl"},
                               {line,287}]}]}}}

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`

**Comment by zhanghongtong** [comment]
When the git command was executed, was the prompt output in Chinese? If so, please change git to English and try again

**Comment by juexun** [comment]
I changed it to English.

(base) ➜  emqx-4.2.2 git:(4b85617) ✗ git status
Not currently on any branch.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   rebar.config.script

no changes added to commit (use "git add" and/or "git commit -a")

But it failed with same error as before.

**Comment by juexun** [comment]
===> Error evaluating configuration script at "/Users/eamon/dev/emqx-4.2.2/_checkouts/emqx_auth_clientid/rebar.config.script":
{error,{55,file,
        {error,badarg,
               [{re,run,
                    [[40,38750,20998,25903,41],
                     "master|^dev/|^hotfix/",
                     [{capture,none}]],
                    []},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,273}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,449}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},
                {file,eval_stream2,6,[{file,"file.erl"},{line,1393}]},
                {file,script,2,[{file,"file.erl"},{line,1090}]},
                {rebar_config,consult_and_eval,2,
                              [{file,"/Users/emqer/code/rebar3/src/rebar_config.erl"},
                               {line,287}]}]}}}

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump

**Comment by zhanghongtong** [comment]
Please execute the command below and tell me the result

```
cd /Users/eamon/dev/emqx-4.2.2/_checkouts/emqx_auth_clientid
git branch | grep -e '^*' | cut -d' ' -f 2
```

**Comment by juexun** [comment]
$ git branch
* (no branch)

$ git branch | grep -e '^*' | cut -d' ' -f 2
(no

**Comment by zhanghongtong** [comment]
The reason for your error is that you execute the git command to output Chinese. I don't understand why you set the English and report the same error. Maybe you can delete the entire project and try again.

**Comment by juexun** [comment]
I rechecked out the source code and modified line 111, 

 $ make
export EMQX_DESC="EMQ X Broker"
/Users/eamon/dev/emqx-4.2.2/rebar3 as emqx release
===> Fetching relup_helper (from {git,"https://github.com/emqx/relup_helper",
                        {branch,"master"}})
===> Compiling relup_helper
===> Fetching rebar3_run (from {git,"https://github.com/emqx/rebar3_run",{tag,"0.2.3"}})
===> Fetching pc (from {git,"https://github.com/emqx/port_compiler.git",{tag,"v1.11.1"}})
===> Compiling pc
===> Compiling rebar3_run
===> Compiling c_src/rebar3_run.c
===> Linking /Users/eamon/dev/emqx-4.2.2/_build/default/plugins/rebar3_run/priv/rebar3_run.so
===> Verifying dependencies...
===> Fetching emqx (from {git,"https://github.com/emqx/emqx",{tag,"v4.2.2"}})
===> Fetching rebar3_proper v0.12.0
===> Version cached at /Users/eamon/.cache/rebar3/hex/hexpm/packages/rebar3_proper-0.12.0.tar is up to date, reusing it
===> Linking _build/default/plugins/rebar3_proper to _build/emqx/plugins/rebar3_proper
===> Compiling rebar3_proper
===> Fetching emqx_auth_clientid (from {git,"https://github.com/emqx/emqx-auth-clientid",
                              {tag,"v4.2.2"}})
===> Error evaluating configuration script at "/Users/eamon/dev/emqx-4.2.2/_build/emqx/lib/emqx_auth_clientid/rebar.config.script":
{error,{55,file,
        {error,badarg,
               [{re,run,
                    [[40,38750,20998,25903,41],
                     "master|^dev/|^hotfix/",
                     [{capture,none}]],
                    []},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,273}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,449}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},
                {file,eval_stream2,6,[{file,"file.erl"},{line,1393}]},
                {file,script,2,[{file,"file.erl"},{line,1090}]},
                {rebar_config,consult_and_eval,2,
                              [{file,"/Users/emqer/code/rebar3/src/rebar_config.erl"},
                               {line,287}]}]}}}

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`

**Comment by zhanghongtong** [comment]
Is your git output in English now?

**Comment by juexun** [comment]
Yes.

$ git status
Not currently on any branch.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   rebar.config.script

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by zhanghongtong** [comment]
How did you modify git

**Comment by juexun** [comment]
alias git='LANG=en_GB git'

**Comment by zhanghongtong** [comment]
Is this setting effective globally? Or is it only effective in the current session?

**Comment by juexun** [comment]
echo "alias git='LANG=en_GB git'" >> ~/.zshrc

And then restart terminal

**Comment by juexun** [comment]
FYI, I can build 4.0.0 successfully.

**Comment by zhanghongtong** [comment]
Execute `erl` to open the erlang console, and enter in it:
```
io:format("~ts",[os:cmd("git branch | grep -e '^*' | cut -d' ' -f 2") -- "\n"]).
```
Please tell me its output

**Comment by juexun** [comment]
1> io:format("~ts",[os:cmd("git branch | grep -e '^*' | cut -d' ' -f 2") -- "\n"]).
(非分支)ok

**Comment by juexun** [comment]
I exported LC_ALL env as follows:
`
$export LC_ALL=en_US.UTF-8
`

It built successfully now.

**Comment by zhanghongtong** [comment]
Great
We will fix this issue later
