### ISSUE TITLE
Emqx failed to run with docker image 

### ISSUE THREAD

**Issue by juexun** [emqx/emqx-rel#613]
#### Environment

- OS:  Mac 10.15
- Erlang/OTP: Erlang/OTP 21
- EMQ: [4.2.2](url)

#### Description

I built docker image successfully. But it failed to run with following output, the `crash.dump` file was attached
[crash.dump.zip](https://github.com/emqx/emqx-rel/files/5577031/crash.dump.zip)

Exec: /opt/emqx/erts-10.7.2.1/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.2.2/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.2.1/../lib -mnesia dir "/opt/emqx/data/mnesia/72995113b659@172.17.0.2" -config /opt/emqx/data/configs/app.2020.11.21.04.48.09.config -args_file /opt/emqx/data/configs/vm.2020.11.21.04.48.09.args -vm_args /opt/emqx/data/configs/vm.2020.11.21.04.48.09.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /opt/emqx
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,bcrypt_nif}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,bcrypt_nif}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: log/crash.dump...done

**Comment by baimeidaxia** [comment]
我也有同样的问题, 请问你是怎么解决的?

**Comment by stm32lou** [comment]
我也遇到同样的问题，最后怎么解决的？谢谢
