### ISSUE TITLE
imagePullSecret missing in helm template

### ISSUE THREAD

**Issue by hmonadjem** [emqx/emqx-rel#620]
#### Description

Our Deployment is in an air-gapped environment so we need to use our own registry which has a username and password. Using your helm template we cannot do this since there is no way of using imagePullSecrets, can we add this please?

**Comment by zhanghongtong** [comment]
Hi, @hmonadjem 
Thanks for your feedback, we'll add it later

**Comment by HJianBo** [comment]
Recently, we have released v4.2.4. Wait a little while and then you can download and try it

**Comment by hmonadjem** [comment]
Great! Thank you!
