### ISSUE TITLE
Time does not match

### ISSUE THREAD

**Issue by Keene-Chen** [emqx/emqx-rel#631]
#### Environment

- OS: Windows Docker Desktop 3.0
- Erlang/OTP: Whatever is included in emqx/emqx Docker container
- EMQ: 4.2.4

#### Description

emqx time is wrong，My time zone difference between China and the US is 8 hours. 
I try to use `docker run -e LC_ALL="en_US.UTF-8" -e TZ="Asia/Shanghai" -d emqx/emqx` 
This setting of nginx image can be changed to Shanghai time zone, but emqx still does not work.

The log is as follows：

```
docker run -e LC_ALL="en_US.UTF-8" -e TZ="Asia/Shanghai" -d nginx
f48adb48c60272619ac18d9d5b5fa9ae91b9aad5806a9a97d4093024ac25e645

docker exec f4 date
Sun Dec 20 23:33:13 CST 2020

docker run -e LC_ALL="en_US.UTF-8" -e TZ="Asia/Shanghai" -d emqx/emqx
16a474faefdc98fd3837d72c5a2e2bfb61baa31639ec58171f27c7fa938ef2c9

docker exec 16 date
Sun Dec 20 15:33:43 UTC 2020
```

I hope to get help, thanks!

**Comment by zhanghongtong** [comment]
Hi, @Hello-Chen 
Sorry for the delay, You can use the following command to change the time zone
```
$ docker run -it --rm -v /etc/localtime:/etc/localtime emqx/emqx:4.2.5 sh
/opt/emqx $ date -R
Tue, 05 Jan 2021 10:40:45 +0800
```
