### ISSUE TITLE
Start EMQX without start.sh in Dockerfile

### ISSUE THREAD

**Issue by hmonadjem** [emqx/emqx-rel#640]
When we start the docker instance it will run the "start.sh", the purpose of the start.sh is basically only to monitor the emqx process. Why is this needed?

We should directly start by running /opt/emqx/bin/emqx foreground, the tool that is responsible for monitoring should be Kubernetes or the Platform you are running this container on.

**Comment by Rory-Z** [comment]
Hi，@hmonadjem
Thanks for your suggestion, we plan to do this in version 4.3, and you can check out this [PR](https://github.com/emqx/emqx/pull/4102/files)
