### ISSUE TITLE
docker-compose.yaml configure dashboard is not valid.

### ISSUE THREAD

**Issue by wkii** [emqx/emqx-rel#647]
#### Environment
emqx docker-compose.yaml configure dashboard is not valid.

```
...
environment:
      - "EMQX_NAME=emqx"
      - "EMQX_LOADED_PLUGINS=emqx_auth_mysql,emqx_management,emqx_recon,emqx_retainer,emqx_rule_engine,emqx_dashboard"
      - "EMQX_ALLOW_ANONYMOUS=false"
      # dashboard default pass to:  dashboard.default_user.password = public
      - "EMQX_DASHBOARD__DEFAULT__USER__PASSWORD=123456"
...
```
this **EMQX_DASHBOARD__DEFAULT__USER__PASSWORD**  is not valid.

- OS: linux
- Erlang/OTP: 
- EMQ: 4.2.7

#### Description

*A description of the issue*

**Comment by HJianBo** [comment]
EMQX_DASHBOARD__DEFAULT__USER__PASSWORD

**Comment by wkii** [comment]
oh ......
Thanks. it's working.
