### ISSUE TITLE
imagePullSecrets per Container

### ISSUE THREAD

**Issue by deen13** [emqx/emqx-rel#648]
I'm stuck in the process of configuring our emqx-broker. My goal is to pull the broker image from a private registry using `image.repository` and `image.pullSecrets`, which apparently was implemented in #620, but applying my manifest results in the following error.

 `UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container`. 

While inspecting the kubernetes api I've noticed that the `imagePullSecrets` field isn't supported on [container level](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#container-v1-core) but on [pod spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#podspec-v1-core) level. 

_Tested on Kubernetes 1.11, 1.19 and 1.20_

**Comment by Rory-Z** [comment]
Hi, @deen13 
Thank you for your feedback
We plan to implement it in 4.3
You are also welcome to contribute to our code

**Comment by deen13** [comment]
Hey @Rory-Z, 

I've create a [pull request ](https://github.com/emqx/emqx-rel/pull/649/files) which fixes the error.

**Comment by deen13** [comment]
Huh! I've just noticed that there is a pending pull request from january which also addresses this issue

**Comment by deen13** [comment]
Huh! I've just noticed that there is a pending pull request from january which also addresses this issue. I'll leave mine open just in case you want an atomic change but feel free to close it otherwise.

**Comment by Rory-Z** [comment]
Oh, Cool, Thanks for the reminder, we almost missed the pull request from january 
After version 4.3, we will build helm chart in the [emqx/emqx](https://github.com/emqx/emqx) repository, which will gradually be deprecated, can you synchronize the changes to [emqx/emqx](https://github.com/emqx/emqx) ?

**Comment by deen13** [comment]
Sure! I'll keep you up to date.

**Comment by deen13** [comment]
@Rory-Z I've made a new pull request against the emqx-repository. :+1:

**Comment by Rory-Z** [comment]
@deen13 Thx
