### ISSUE TITLE
Configuration changes don't restart Kubernetes pod

### ISSUE THREAD

**Issue by nicklasfrahm** [emqx/emqx-rel#650]
#### Environment

- OS: emqx/emqx Docker container
- Erlang/OTP: R22/10.7.2.6
- EMQ: 4.2.8

#### Description

If the environment variable configuration changes and thus the `emqx-env` configmap, the pod will not be restarted and the changes will not be applied. This can be tested by installing with `--set "emqxConfig.EMQX_ALLOW_ANONYMOUS=true"`. Upgrading the helm chart afterwards with `--set "emqxConfig.EMQX_ALLOW_ANONYMOUS=false"` will modify the `emqx-env` configmap, but not restart the pod.

Possibly related to this: https://github.com/kubernetes/kubernetes/issues/22368

With this issue it is hard to apply configuration changes via helm upgrades.

**Comment by Rory-Z** [comment]
Hi, @nicklasfrahm 
I think the pod should not be restarted easily, which may cause problems in the production business. I think users can manually update the `statefulset` through `kubectl`

**Comment by nicklasfrahm** [comment]
Thank you for your response @Rory-Z. I understand this use case, but it might be nice to have a configuration option in the Helm Chart then to disable the use of a `ConfigMap`, because this allows your CI to update the configuration.

**Comment by Rory-Z** [comment]
Yes, it‘s cool, can you contribute code to us? This repository will no longer be maintained after version 4.3, you can see our code [here](https://github.com/emqx/emqx/tree/master/deploy/charts/emqx)

**Comment by nicklasfrahm** [comment]
Closing this in favor of emqx/emqx#4897.
