### ISSUE TITLE
helm install emqx   Custom EMQX_LOADED_PLUGINS 

### ISSUE THREAD

**Issue by liuxingjun** [emqx/emqx-rel#660]
#### Environment

- EMQ: 4.3.5

#### Description

###Repetition steps

```
# helm3 search repo emqx
NAME            CHART VERSION   APP VERSION     DESCRIPTION                             
emqx/emqx       4.3.5           4.3.5           A Helm chart for EMQ X                  
emqx/emqx-ee    4.2.6           4.2.6           A Helm chart for EMQ X Enterprise       
emqx/kuiper     0.9.0           0.9.0           A lightweight IoT edge analytic software
```

add env  EMQX_LOADED_PLUGINS to values.yaml
``` 
emqxConfig:
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  ## The address type is used to extract host from k8s service.
  ## Value: ip | dns | hostname
  ## Note：Hostname is only supported after v4.0-rc.2
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  ## if EMQX_CLUSTER__K8S__ADDRESS_TYPE eq dns
  # EMQX_CLUSTER__K8S__SUFFIX: "pod.cluster.local"
  EMQX_LOADED_PLUGINS: "emqx_dashboard"
```

run `helm3 install connliu  -n connliu  emqx/emqx -f values.yaml`
```shell
# kubectl get pod -n connliu
NAME             READY   STATUS             RESTARTS   AGE
connliu-emqx-0   0/1     CrashLoopBackOff   1          8s
```

```shell
# kubectl logs -n connliu  connliu-emqx-0 emqx 
EMQX_LOADED_PLUGINS=emqx_dashboard
/usr/bin/docker-entrypoint.sh: line 101: /opt/emqx/data/loaded_plugins: Read-only file system
```

### Normal helm install 
```
# helm3 install  connliu -n connliu  emqx/emqx
NAME: connliu
LAST DEPLOYED: Fri Jul 16 11:39:49 2021
NAMESPACE: connliu
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pod -n connliu 
NAME             READY   STATUS    RESTARTS   AGE
connliu-emqx-0   1/1     Running   0          13s

# kubectl exec -it -n connliu connliu-emqx-0 -- ls -l /opt/emqx/data/
total 24
drwxrwxr-x    2 emqx     emqx          4096 Jul 16 03:39 configs
-rw-r--r--    1 root     emqx           177 Jul 16 03:39 loaded_modules
-rw-r--r--    1 root     emqx           169 Jul 16 03:39 loaded_plugins
drwxrwsrwx    3 root     emqx          4096 Jul 16 03:39 mnesia
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 patches
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 scripts
```
The permissions of directories `loaded_modules` and `loaded_plugins` are different from others 

### Custom  EMQX_LOADED_PLUGINS docker  install 
```
# docker run -d --name emqx -p 18083:18083 -e EMQX_LOADED_PLUGINS="emqx_dashboard" emqx/emqx:4.3.5
189f7061d4e8ca2a96211baf3930ff0770e5f6deb3c264f3405287b59ac4e20d

# docker exec emqx ls -l /opt/emqx/data/
total 24
drwxrwxr-x    2 emqx     emqx          4096 Jul 16 03:34 configs
-rw-rw-r--    1 emqx     emqx            58 Jun 28 06:54 loaded_modules
-rw-rw-r--    1 emqx     emqx           192 Jul 16 03:34 loaded_plugins
drwxrwxr-x    3 emqx     emqx          4096 Jul 16 03:34 mnesia
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 patches
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 scripts
```

**Comment by iMadriver** [comment]
Hi， did you solved your issue? I hope to start "emqx_auth_mnesia" with helm commands, and  result in "CrashLoopBackOff".

**Comment by liuxingjun** [comment]
> Hi， did you solved your issue? I hope to start "emqx_auth_mnesia" with helm commands, and result in "CrashLoopBackOff".

You can use `kubectl logs` to see if this is the same problem as mine

**Comment by liuxingjun** [comment]
> Hi， did you solved your issue? I hope to start "emqx_auth_mnesia" with helm commands, and result in "CrashLoopBackOff".

I use `4.2.13` temporarily available

**Comment by iMadriver** [comment]
My emqx/emqx version is 4.3.5. And after I added `EMQX_LOADED_PLUGINS: "emqx_auth_mnesia"` in values.yaml, it seems ok but nothing changes. The `emqx_auth_mnesia` is still not started, verifired in dashboard.

**Comment by iMadriver** [comment]
> > Hi， did you solved your issue? I hope to start "emqx_auth_mnesia" with helm commands, and result in "CrashLoopBackOff".
> 
> You can use `kubectl logs` to see if this is the same problem as mine

I checked the log and got ` [error] [Plugins] Write File "data/loaded_plugins" Error: erofs
`, seems the same as your issue

**Comment by liuxingjun** [comment]
> > > Hi， did you solved your issue? I hope to start "emqx_auth_mnesia" with helm commands, and result in "CrashLoopBackOff".
> > 
> > 
> > You can use `kubectl logs` to see if this is the same problem as mine
> 
> I checked the log and got `[error] [Plugins] Write File "data/loaded_plugins" Error: erofs`, seems the same as your issue

use version  4.2.13 for the time being
`helm3 install  test  emqx/emqx -f values.yaml  --version 4.2.13`

**Comment by iMadriver** [comment]
> > > > Hi， did you solved your issue? I hope to start "emqx_auth_mnesia" with helm commands, and result in "CrashLoopBackOff".
> > > 
> > > 
> > > You can use `kubectl logs` to see if this is the same problem as mine
> > 
> > 
> > I checked the log and got `[error] [Plugins] Write File "data/loaded_plugins" Error: erofs`, seems the same as your issue
> 
> use version 4.2.13 for the time being
> `helm3 install test emqx/emqx -f values.yaml --version 4.2.13`

wonderful!

**Comment by lpaulusLohr** [comment]
Update, I have same issue with 4.3.8 need to rollback to 4.2.13

**Comment by gcdd1993** [comment]
mark, I have same issue with 4.3.11

**Comment by barisvelioglu** [comment]
Same issue as well.

**Comment by ylcrow** [comment]
kubectl   edit  configmap xxxx--loaded-plugins

**Comment by xiemeilong** [comment]
Same issue as well with 4.4.2

**Comment by zhonghuali** [comment]
Same issue as well with latest version 4.4.19, but docker run work fine.

**Comment by Rory-Z** [comment]
Hi guys, now EMQ X no longer uses this repository since version 4.3. Use https://github.com/emqx/emqx/ instead.
